spring:
  application:
    name: ApiGetaway

  #Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/ticketing-security-realm

keycloak:
  auth:
    jwk-set-uri: http://localhost:8091/realms/ticketing-security-realm/protocol/openid-connect/certs

server:
  port: 8090

app:
  backend:
    booking-service: http://localhost:8081/
    inventory-service: http://localhost:8080/