spring:
  application:
    name: ApiGateway

  # Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/ticketing-security-realm

# OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Inventory Service
        url: /docs/inventory-service/v3/api-docs
      - name: Booking Service
        url: /docs/booking-service/v3/api-docs
  api-docs:
    path: /v3/api-docs

# Actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# Resilinece4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 8
        failure-rate-threshold: 50
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

server:
  port: 8090

# Keycloak variable
keycloak:
  auth:
    jwk-set-uri: http://localhost:8091/realms/ticketing-security-realm/protocol/openid-connect/certs

# Routes variables
app:
  backend:
    booking-service: http://localhost:8081/
    inventory-service: http://localhost:8080/

# security config variables
security:
  excluded:
    urls: /swagger-ui.html, /swagger-ui/**,/docs/**,/v3/api-docs/**,/swagger-resources/**,/api-docs/**

#logging:
#  level:
#    root: debug

